/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudienciasRouteImport } from './routes/audiencias'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolucionesRouteImport } from './routes/soluciones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienciasRoute = AudienciasRouteImport.update({
  id: '/audiencias',
  path: '/audiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucionesRoute = SolucionesRouteImport.update({
  id: '/soluciones',
  path: '/soluciones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiencias': typeof AudienciasRoute
  '/campus': typeof CampusRoute
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiencias': typeof AudienciasRoute
  '/campus': typeof CampusRoute
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiencias': typeof AudienciasRoute
  '/campus': typeof CampusRoute
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audiencias'
    | '/campus'
    | '/contacto'
    | '/sitemap.xml'
    | '/soluciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiencias'
    | '/campus'
    | '/contacto'
    | '/sitemap.xml'
    | '/soluciones'
  id:
    | '__root__'
    | '/'
    | '/audiencias'
    | '/campus'
    | '/contacto'
    | '/sitemap.xml'
    | '/soluciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudienciasRoute: typeof AudienciasRoute
  CampusRoute: typeof CampusRoute
  ContactoRoute: typeof ContactoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolucionesRoute: typeof SolucionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiencias': {
      id: '/audiencias'
      path: '/audiencias'
      fullPath: '/audiencias'
      preLoaderRoute: typeof AudienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones': {
      id: '/soluciones'
      path: '/soluciones'
      fullPath: '/soluciones'
      preLoaderRoute: typeof SolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudienciasRoute: AudienciasRoute,
  CampusRoute: CampusRoute,
  ContactoRoute: ContactoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolucionesRoute: SolucionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
